### ISSUE TITLE
./cleandb fails during password inputs

### ISSUE THREAD

**Issue by OleMussmann** [SNStatComp/ckan-CC#2]
```
Error response from daemon: No such container: ckan
DROP DATABASE
DROP ROLE
CREATE ROLE
CREATE DATABASE
Initialising DB: SUCCESS
psql:sql/clean_01_init_datastore.sql:1: NOTICE:  role "datastore_user" does not exist, skipping
DROP ROLE
psql:sql/clean_01_init_datastore.sql:2: NOTICE:  database "datastore_default" does not exist, skipping
DROP DATABASE
CREATE ROLE
CREATE DATABASE
psql (9.3.14, server 9.5.4)
WARNING: psql major version 9.3, server major version 9.5.
         Some psql features might not work.
You are now connected to database "datastore_default" as user "postgres".
REVOKE
REVOKE
GRANT
GRANT
GRANT
GRANT
REVOKE
GRANT
GRANT
GRANT
ALTER DEFAULT PRIVILEGES
Warning: Password input may be echoed.
Password: Traceback (most recent call last):
  File "/usr/local/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 754, in command
    self.add()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 845, in add
    data_dict['password'] = self.password_prompt()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 820, in password_prompt
    password1 = getpass.getpass('Password: ')
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
EOFError
Warning: Password input may be echoed.
Password: Traceback (most recent call last):
  File "/usr/local/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 754, in command
    self.add()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 845, in add
    data_dict['password'] = self.password_prompt()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 820, in password_prompt
    password1 = getpass.getpass('Password: ')
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
EOFError
Warning: Password input may be echoed.
Password: Traceback (most recent call last):
  File "/usr/local/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 754, in command
    self.add()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 845, in add
    data_dict['password'] = self.password_prompt()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 820, in password_prompt
    password1 = getpass.getpass('Password: ')
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
EOFError
Warning: Password input may be echoed.
Password: Traceback (most recent call last):
  File "/usr/local/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 754, in command
    self.add()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 845, in add
    data_dict['password'] = self.password_prompt()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 820, in password_prompt
    password1 = getpass.getpass('Password: ')
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
EOFError
Warning: Password input may be echoed.
Password: Traceback (most recent call last):
  File "/usr/local/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 754, in command
    self.add()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 845, in add
    data_dict['password'] = self.password_prompt()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 820, in password_prompt
    password1 = getpass.getpass('Password: ')
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
EOFError
Warning: Password input may be echoed.
Password: Traceback (most recent call last):
  File "/usr/local/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 754, in command
    self.add()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 845, in add
    data_dict['password'] = self.password_prompt()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 820, in password_prompt
    password1 = getpass.getpass('Password: ')
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
EOFError
```

**Comment by OleMussmann** [comment]
Having an up-to-date passfile fixed it for me. Thanks Alex!
